### ISSUE TITLE
Composer package is out of date

### ISSUE THREAD

**Issue by mickaelperrin** [agaluf/vatty#1]
Hey,

Thanks for this useful library.

I just installed it with composer and it wasn't working due to the lack of "meng-tian/async-soap-guzzle" dependency.

I see that the dependency has been added but a new release hasn't been performed. Could you pack the bugfix ?

Thanks,

**Comment by agaluf** [comment]
Expect a new release tomorrow (CET) that will patch this

**Comment by agaluf** [comment]
I have just pushed a new release that fixes the issue.
