### ISSUE TITLE
FR VAT validation doesn't work

### ISSUE THREAD

**Issue by mickaelperrin** [agaluf/vatty#2]
Hey,

I just tried your library with my own VAT number. I realize that it doesn't pass the regex check.

I updated it to `FR[0-9A-Z]{2}[0-9]{9}` to get it working, but I guess you should have some kind of official regex patterns?

My VAT number has numbers after the FR and I don't know if it should also handle letters. 

My vat number has also spaces, but the vies validation doesn't work if they are set.

**Comment by agaluf** [comment]
Hello, thank you for your pull. According to Vies FAQ, the first two symbols in French VAT should be characters. If that includes numbers, I need to update the tests and the code. I’ll update the library to trim the spaces by default.

**Comment by agaluf** [comment]
The fix has been included in the new release. Thank you for reporting this issue.
